version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"

  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .G:/sistema
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data: